# this is ad-web-vi project's deploy shell by docker
# create date: 2022/03/24

version: "3"

services:
  webapp:
    image: "node:14"
    user: "root"
    working_dir: "/app/ad-web-vi"
    ports:
      [8999:3000]
    volumes:
      - $PWD/:/app/ad-web-vi
    command:
      - /bin/sh
      - -c
      - |
        echo 'run the bash command..'
        npm -v
        npm config set registry https://registry.npm.taobao.org
        npm install -g yarn
        cd /app/ad-web-vi
        yarn install
        yarn build
        nohup yarn start &
        echo 'success.. start..'
        pwd
        echo '查看输出:...'
        cat nohup.out
        tail -f /dev/null
    tty: true
    stdin_open: true
